//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podaci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobil()
        {
            this.Najams = new HashSet<Najam>();
        }
    
        public int id_automobil { get; set; }
        public int id_model { get; set; }
        public int id_marka { get; set; }
        public int id_status { get; set; }
        public int id_lokacija { get; set; }
        public string tablica { get; set; }
        public int godiste { get; set; }
        public decimal cijena_po_danu { get; set; }
        public byte[] slika { get; set; }
        public int snaga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Najam> Najams { get; set; }
        public virtual Lokacija Lokacija { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Model Model { get; set; }
        public virtual Status Status { get; set; }

        public override string ToString()
        {
            return Marka.ToString() + " " + Model.ToString();
        }
    }
}
